### ISSUE TITLE
Latin Hypercube Sampling with multi-dimensional uniformity (lhsmdu)

### ISSUE THREAD

**Issue by debipe20** [tisimst/pyDOE#13]
how to install Latin Hypercube Sampling with multi-dimensional uniformity (lhsmdu) packages in python & anaconda?

**Comment by tisimst** [comment]
Not sure about anaconda (since I don't use that), but normal installation method would be to download the latest master from the [lhsmdu github repo](https://github.com/sahilm89/lhsmdu), unzip it, then navigate to the unzipped folder on the command line and run `python setup.py install`.

**Comment by debipe20** [comment]
I have found this error:
Collecting setup.py
  Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py

**Comment by tisimst** [comment]
Is that the entire output when you tried to install it? If you wouldn't mind being a bit more verbose in what you've done so far, that would help me understand why you're getting the error.

**Comment by debipe20** [comment]
I have got this while i tried to install this. 
At first, I download the zip file then unzip it and placed unzip folder in my python folder. After that I run my command shell and went to python directory and put this command python setup.py install .
Then I got that error. Is there anyway to install via pip command?

**Comment by tisimst** [comment]
Don't worry about placing the unzipped folder in the python folder. The installer takes care of that. Place the unzipped folder wherever you can find it (like your desktop folder). Now, open a command line and navigate to the unzipped folder using the command line. Now, simply type what I said before: `python setup.py install` and that should place any files you need into your Python packages folder.

It doesn't look like the lhsmdu author has published the package to the Python Package Index (PYPI), so pip or the likes will not work. You might contact the author about it though since installation would be much simpler. In fact, it's probably better to send any further questions to the lhsmdu author rather than here since I don't have anything to do with it. Just open an issue on their github repository. Thanks and good luck!
